# application.yml

## Configuración para Eureka (solo local o desarrollo)
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port:8080}
    secure-port: 443

## Configuración Spring y Base de Datos local (PostgreSQL)
spring:
  application:
    name: ${APP_NAME:microservice}

  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:microservice}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
